### ISSUE TITLE
Feature Reques seperate IO

### ISSUE THREAD

**Issue by LaneaLucy** [EtchedPixels/RC2014#38]
i would love to have a separate file that handles IO so it would be easier to implement new IO,
so someone could first implement them here and test the principles/Idea before trying to implement them in hardware.

i like the idea how it is done in https://github.com/BleuLlama/z80-machine but this project only includes the z80 processor. But i need Z180.

Thx for your time, have a great day

LaneaLucy

**Comment by EtchedPixels** [comment]
Not entirely sure what you asking for. The Z180 emulator is a library so you can plug it into anything, likewise a lot of the device emulations are their own file so that it can just be plugged into a platform.

Can you explain more what you mean as I already use these emulators to test hardware concepts before putting hardware together, and to write device drivers before it arrives.
